export { api } from './config';
export { authService } from './auth';
export type { User, LoginResponse, RegisterData } from './auth';
export { productsService } from './products';
export type { Product, ProductImage, ProductFilters, ProductsResponse } from './products';
export { categoriesService } from './categories';
export type { Category } from './categories';
export { favoritesService } from './favorites';
export { ordersService } from './orders';
export type { Order, OrderStats } from './orders';
export { cartService } from './cart';
export type { CartItem, CartSummary, CartResponse } from './cart';
export { subscriptionsService } from './subscriptions';
export type { SubscriptionPlan, SubscriptionStatus, PixPayment, BoletoPayment } from './subscriptions';
export { messagesService } from './messages';
export type { Conversation, Message } from './messages';
export { addressesService } from './addresses';
export type { Address } from './addresses';
export { aiService } from './ai';
export type { ClothingAnalysis, ImageEnhanceResult, BackgroundRemovalResult, VirtualTryOnResult } from './ai';
export { shippingService } from './shipping';
export type { ShippingOption, ShippingLabel, TrackingEvent, TrackingInfo } from './shipping';
export { tagsService } from './tags';
export type { Tag, TagsResponse } from './tags';
export { usersService } from './users';
export type { SellerProfile, SellerProduct } from './users';
